# Generated by Django 4.0.2 on 2022-03-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
    ]
